### ISSUE TITLE
FPGA opend

### ISSUE THREAD

**Issue by Bloatamus** [captain-amygdala/pistorm#41] opened 2021-08-22 10:09 UTC
Hi, Unable to flash nprog

Open On-Chip Debugger 0.10.0+dev-00114-g41bcbc67d-dirty (2021-01-18-16:43)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : BCM2835 GPIO JTAG/SWD bitbang driver
Info : clock speed 100 kHz
Error: JTAG scan chain interrogation failed: all zeroes
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: max2.tap: IR capture error; saw 0x0 not 0x1
Warn : Bypassing JTAG setup events due to errors
Warn : gdb services need one or more targets defined
svf processing file: "./rtl/EPM240_bitstream.svf"
adapter speed: 100 kHz

Error: tdo check error at line 53
Error:     READ = 0x000
Error:     WANT = 0x8232
Error:     MASK = 0xffff
Error: fail to run command at line 1066
Error: tdo check error at line 53
Error:     READ = 0x000
Error:     WANT = 0x8232
Error:     MASK = 0xffff
Time used: 0m0s920ms
svf file programmed failed

Pi 3 Model A+

Any heo would be appreciated, Thank you

**Comment by captain-amygdala** [comment] 2021-08-22 10:56
Hi!
Looks like the TDO pin of the CPLD, for whatever reason, is stuck at 0.
I would check for bad soldering and other obvious things.
Also make sure the emulation is not running while you try to update the CPLD.

I close this Issue, as its not a bug of PiStorm but rather a error on the PCB you have.

**Closed by captain-amygdala** 2021-08-22 10:56 UTC
